extends: airbnb/base
plugins:
  - react
rules:
  react/jsx-uses-vars:
    - 1
  no-unused-vars:
    - 2
    - args: after-used
      argsIgnorePattern: ^_
globals:
  m: true,
  $: true,
  jQuery: true,
  browser: true
env:
  mocha: true
parserOptions:
  ecmaFeatures:
    jsx: true
